// let umaString = 'Um "texto"';
// let umaString = "Um \"texto\"";
// let umaString = `Um \\texto`;
let umaString = "Um texto";
console.log(umaString);
console.log(umaString[4]);
console.log(umaString[8]);
console.log(umaString.concat(' em um lindo dia'));
console.log(umaString + ' Outro texto');
console.log(umaString.indexOf('texto'));
console.log(umaString.lastIndexOf('t', 2));
console.log(umaString.lastIndexOf('t', 3));
console.log(umaString.match(/[a-z]/g));
console.log(umaString.match(/[a-z]/));
console.log(umaString.search(/a-z/g));
console.log(umaString.search(/a-z/));
console.log(umaString.replace('Um', 'Mudando a palavra "Um"'));
console.log(umaString.replace(/Um/, 'Mudando a palavra "Um"'));
console.log(umaString.length);
console.log(umaString.slice(3, 8));
console.log(umaString.slice(-2));
console.log(umaString.slice(-2, -1));
console.log(umaString.substring(3, 8));
console.log(umaString.split(' '));
console.log(umaString.toUpperCase());
console.log(umaString.toLowerCase());