// olhar a documetação para estudar o objeto math
let num1 = 9.54578;
let num2 = Math.floor(num1);
console.log(num2);
let num3 = Math.ceil(num1);
console.log(num3);
let num4 = Math.round(num1);
console.log(num4);
console.log(Math.max(1, 2, 3, 4, 5, 6, 7, 8, 9));
console.log(Math.min(1, 2, 3, 4, 5, 6, 7, 8, 9));
console.log(Math.random());
const aleatorio = Math.round(Math.random() * (10 - 5) + 5);
console.log(aleatorio);
console.log(Math.PI);
console.log(Math.pow(2, 10));
console.log(2 ** 10);
console.log(9 **(1 / 2));
console.log(Math.sqrt(16));
console.log(100 / 0);
console.log(!!(100 / 0));