// const alunos = 'Luiz, Maria, João, Ana';
// const alunos = ['Luiz', 'Maria', 'João', 'Ana', 1, true, null, undefined, { nome: 'Luiz' }, ['Luiz', 'Maria']];
const nome = 'Luiz';
console.log(nome[0]);
const alunos = ['Luiz', 'Maria', 'João', 'Ana'];
alunos[0] = 'Eduardo';
alunos[4] = 'Luiza';
alunos.push('Felipe');
alunos[alunos.length] = 'Pedro';
alunos.unshift('Luiza');
const removido = alunos.pop();
const removidoInicio = alunos.shift();
delete alunos[1];
console.log(removido);
console.log(removidoInicio);
console.log(alunos[0]);
console.log(alunos);
console.log(alunos[100]);
console.log(alunos.slice(0, 3));
console.log(typeof alunos);
console.log(alunos instanceof Array);